"use client";
import React, { useState, useEffect } from 'react';
import { motion } from 'motion/react';
import { FileText, Shield, Cookie, HeartPulse, ArrowLeft } from 'lucide-react';
import { Language } from '../types';
import { TRANSLATIONS } from '../data';

interface LegalProps {
  language: Language;
  onBack: () => void;
  initialDoc?: 'terms' | 'privacy' | 'cookie' | 'hipaa';
}

export default function Legal({ language, onBack, initialDoc = 'privacy' }: LegalProps) {
  const isRtl = language === 'ar';
  const t = TRANSLATIONS[language];

  const [activeTab, setActiveTab] = useState<'terms' | 'privacy' | 'cookie' | 'hipaa'>(initialDoc);

  useEffect(() => {
    setActiveTab(initialDoc);
  }, [initialDoc]);

  const tabs = [
    { id: 'terms' as const, label: t.footerTerms || 'Terms & Conditions', icon: FileText },
    { id: 'privacy' as const, label: t.footerPrivacy || 'Privacy Policy', icon: Shield },
    { id: 'cookie' as const, label: t.footerCookieNotice || 'Cookie Notice', icon: Cookie },
    { id: 'hipaa' as const, label: t.footerHIPAA || 'HIPAA Compliance', icon: HeartPulse },
  ];

  const content = {
    en: {
      terms: {
        title: 'Terms & Conditions',
        subtitle: 'Last Updated: June 23, 2026',
        sections: [
          {
            heading: '1. Acceptance of Terms',
            body: 'By accessing or using the AutiCare platform, you agree to be bound by these Terms & Conditions. If you do not agree to all of these terms, do not use our services.'
          },
          {
            heading: '2. Clinical Disclaimer',
            body: 'AutiCare is an artificial intelligence decision-support tool designed for parents and clinicians. The insights, nutrition suggestions, and meltdown risk predictions generated by the AI are for informational purposes only and DO NOT constitute professional medical advice, diagnosis, or treatment. Always consult with a licensed pediatrician, therapist, or qualified healthcare provider regarding medical decisions.'
          },
          {
            heading: '3. User Accounts',
            body: 'You are responsible for safeguarding the credentials you use to access the platform. Clinicians must verify their identity and clinical licenses before accessing patient records. Parents are solely responsible for ensuring the correctness of the child profiles they initialize.'
          },
          {
            heading: '4. Limitation of Liability',
            body: 'To the maximum extent permitted by applicable law, AutiCare and its developers shall not be liable for any direct, indirect, incidental, special, or consequential damages resulting from the use or inability to use the platform.'
          }
        ]
      },
      privacy: {
        title: 'Privacy Policy',
        subtitle: 'Last Updated: June 23, 2026',
        sections: [
          {
            heading: '1. Information We Collect',
            body: 'We collect information you provide directly to us, including full names, email addresses, phone numbers, child profile details (age, diagnosis level), daily behavioral tracking logs, and uploaded genetic/medical reports.'
          },
          {
            heading: '2. Protected Health Information (PHI)',
            body: 'We treat all child diagnostic levels, genetic markers, and behavioral tracker logs as Protected Health Information (PHI) under HIPAA guidelines. These records are encrypted end-to-end and tokenized to ensure that personal identities are segregated from medical data.'
          },
          {
            heading: '3. How We Use Data',
            body: 'Data is used solely to generate meltdown risk predictions, construct genetic-nutrition plans, and coordinate notes between parents and clinicians. We DO NOT sell, rent, or monetize your health or personal data under any circumstances.'
          },
          {
            heading: '4. Data Security & Retention',
            body: 'We store data in highly secure MongoDB Atlas databases employing 256-bit AES encryption at rest and TLS encryption in transit. Personal data will be retained only as long as necessary to fulfill the purposes outlined in this policy or as required by regulatory compliance.'
          }
        ]
      },
      cookie: {
        title: 'Cookie Notice',
        subtitle: 'Last Updated: June 23, 2026',
        sections: [
          {
            heading: '1. What Are Cookies?',
            body: 'Cookies are small text files placed on your device to store data that can be recalled by a web server. We use cookies and similar tracking tokens (such as session storage) to identify your authenticated user state and preserve language preferences.'
          },
          {
            heading: '2. Types of Cookies We Use',
            body: 'We use essential session cookies to keep you logged in to your account securely. Performance cookies may also be utilized in production to monitor load times and backend API query latency under Vercel serverless containers.'
          },
          {
            heading: '3. Consent Management',
            body: 'By continuing to navigate the AutiCare platform, you consent to the use of essential session and authentication cookies. You can manage or disable cookie tracking in your browser settings, but doing so will prevent you from logging into the portal.'
          }
        ]
      },
      hipaa: {
        title: 'HIPAA Compliance',
        subtitle: 'Last Updated: June 23, 2026',
        sections: [
          {
            heading: '1. Administrative Safeguards',
            body: 'AutiCare maintains strict operational protocols to govern access to Protected Health Information (PHI). Only authorized clinical staff mapped to a patient profile are allowed to review logs, and audit logs track every record access or update.'
          },
          {
            heading: '2. Physical Safeguards',
            body: 'Our database and cloud services are hosted in enterprise MongoDB Atlas and Vercel environments that satisfy physical security specifications, including biometric access control, 24/7 security surveillance, and multi-zone hardware redundancy.'
          },
          {
            heading: '3. Technical Safeguards',
            body: 'We employ 256-bit AES encryption for all database records at rest and secure SSL/TLS sockets for API endpoints. In-app sessions automatically expire after 15 minutes of inactivity, and passwords are encrypted using strong salted hashing algorithms (Bcrypt).'
          },
          {
            heading: '4. Business Associate Agreement (BAA)',
            body: 'AutiCare signs HIPAA Business Associate Agreements (BAA) with licensed medical clinics and healthcare provider networks before activating clinical portals to guarantee compliance with the HITECH Act and HIPAA Omnibus Rules.'
          }
        ]
      }
    },
    ar: {
      terms: {
        title: 'الشروط والأحكام',
        subtitle: 'آخر تحديث: 23 يونيو 2026',
        sections: [
          {
            heading: '1. قبول الشروط',
            body: 'باستخدامك لمنصة AutiCare، فإنك توافق على الالتزام بشروط الخدمة والأحكام هذه. إذا كنت لا توافق على هذه الشروط، يرجى عدم استخدام خدماتنا.'
          },
          {
            heading: '2. إخلاء المسؤولية الطبية',
            body: 'تعد AutiCare أداة دعم قرار قائمة على الذكاء الاصطناعي مخصصة للآباء والأخصائيين. إن التحليلات واقتراحات التغذية وتوقعات مخاطر النوبات التي يتم إنشاؤها هي لأغراض إعلامية فقط ولا تشكل نصيحة طبية أو تشخيصاً أو علاجاً مهنياً. استشر دائماً طبيب الأطفال أو المعالج المؤهل قبل اتخاذ أي قرارات طبية.'
          },
          {
            heading: '3. حسابات المستخدمين',
            body: 'أنت مسؤول عن حماية بيانات الاعتماد المستخدمة للوصول للمنصة. يجب على الأطباء والمعالجين التحقق من هوياتهم وتراخيصهم المهنية قبل الوصول لملفات الأطفال. كما يتحمل الآباء المسؤولية الكاملة عن صحة البيانات المدخلة في ملفات أطفالهم.'
          },
          {
            heading: '4. حدود المسؤولية',
            body: 'بأقصى حد يسمح به القانون المعمول به، لن تكون AutiCare أو مطوروها مسؤولين عن أي أضرار مباشرة أو غير مباشرة أو عرضية أو تبعية تنتج عن استخدام أو عدم القدرة على استخدام المنصة.'
          }
        ]
      },
      privacy: {
        title: 'سياسة الخصوصية',
        subtitle: 'آخر تحديث: 23 يونيو 2026',
        sections: [
          {
            heading: '1. المعلومات التي نجمعها',
            body: 'نجمع المعلومات التي تقدمها لنا مباشرة، بما في ذلك الاسم الكامل، البريد الإلكتروني، رقم الهاتف، تفاصيل ملف الطفل (العمر، مستوى التوحد)، سجلات السلوك اليومية، والتقارير الطبية والجينية المرفوعة.'
          },
          {
            heading: '2. حماية المعلومات الصحية (PHI)',
            body: 'نتعامل مع مستويات التشخيص، الجينات، وسجلات السلوك اليومية للأطفال باعتبارها معلومات صحية محمية بموجب توجيهات HIPAA. يتم تشفير هذه السجلات بالكامل بين الطرفين (End-to-End) وفصل الهويات الشخصية عن البيانات الطبية.'
          },
          {
            heading: '3. كيفية استخدام البيانات',
            body: 'تُستخدم البيانات فقط لإنشاء توقعات مخاطر نوبات التوحد، ووضع خطط التغذية الجينية، وتنسيق الملاحظات الطبية بين الآباء والعيادات. نحن لا نقوم ببيع أو مشاركة أو استغلال بياناتك الصحية لأغراض تجارية تحت أي ظرف.'
          },
          {
            heading: '4. أمن البيانات والاحتفاظ بها',
            body: 'نقوم بتخزين البيانات في قواعد بيانات MongoDB Atlas شديدة الأمان باستخدام تشفير AES ذو 256 بت أثناء الخمول وتشفير TLS أثناء النقل. سيتم الاحتفاظ بالبيانات فقط للمدة اللازمة لتحقيق الأغراض الموضحة أو بما يتوافق مع القوانين.'
          }
        ]
      },
      cookie: {
        title: 'إشعار ملفات تعريف الارتباط (Cookies)',
        subtitle: 'آخر تحديث: 23 يونيو 2026',
        sections: [
          {
            heading: '1. ما هي ملفات تعريف الارتباط؟',
            body: 'ملفات تعريف الارتباط هي ملفات نصية صغيرة يتم وضعها على جهازك لحفظ البيانات التي يمكن استدعاؤها لاحقاً. نستخدم ملفات تعريف الارتباط ورموز تتبع الجلسات للحفاظ على تسجيل دخولك وحفظ تفضيلات اللغة.'
          },
          {
            heading: '2. أنواع ملفات تعريف الارتباط المستخدمة',
            body: 'نستخدم ملفات تعريف الارتباط الأساسية للحفاظ على أمان حسابك أثناء تصفح البوابة. قد نستخدم أيضاً ملفات تعريف ارتباط لتحسين الأداء وقياس أوقات استجابة واجهات برمجة التطبيقات على خوادم Vercel.'
          },
          {
            heading: '3. إدارة الموافقة',
            body: 'باستمرارك في تصفح منصة AutiCare، فإنك توافق على استخدام ملفات تعريف الارتباط الأساسية. يمكنك تعطيل ملفات تعريف الارتباط من إعدادات متصفحك، ولكن هذا قد يمنعك من تسجيل الدخول واستخدام البوابة.'
          }
        ]
      },
      hipaa: {
        title: 'امتثال معايير HIPAA',
        subtitle: 'آخر تحديث: 23 يونيو 2026',
        sections: [
          {
            heading: '1. الضمانات الإدارية',
            body: 'تلتزم AutiCare ببروتوكولات تشغيلية صارمة للتحكم في الوصول إلى المعلومات الصحية المحمية (PHI). يُسمح فقط للأخصائيين المرتبطين بملف الطفل بمراجعة السجلات، وتتبع سجلات التدقيق الأمني كل عملية وصول أو تحديث للبيانات.'
          },
          {
            heading: '2. الضمانات المادية',
            body: 'تتم استضافة خدمات السحاب وقواعد البيانات الخاصة بنا في بيئات MongoDB Atlas و Vercel المعتمدة للمؤسسات والتي تلبي متطلبات الأمن المادي، بما في ذلك التحكم في الوصول البيومتري، والمراقبة الأمنية على مدار الساعة.'
          },
          {
            heading: '3. الضمانات التقنية',
            body: 'نستخدم تشفير AES ذو 256 بت لجميع السجلات المخزنة وقنوات SSL/TLS آمنة لجميع اتصالات الشبكة. تنتهي جلسات العمل تلقائياً بعد 15 دقيقة من الخمول، ويتم تشفير كلمات المرور باستخدام خوارزميات التمليح القوية (Bcrypt).'
          },
          {
            heading: '4. اتفاقية شريك العمل (BAA)',
            body: 'توقع AutiCare اتفاقيات شريك العمل (BAA) المعتمدة مع العيادات المرخصة وشبكات الرعاية الصحية قبل تفعيل بوابات العيادات لضمان الامتثال لقانون HITECH وقواعد HIPAA الكاملة.'
          }
        ]
      }
    }
  };

  const doc = content[language][activeTab] || content['en'][activeTab];

  return (
    <div className="max-w-5xl mx-auto my-12 px-4 select-none">
      <motion.div
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-white rounded-3xl border border-sky-100 shadow-xl overflow-hidden"
      >
        {/* Banner header */}
        <div className="bg-slate-900 px-6 sm:px-8 py-8 text-white relative overflow-hidden">
          <div className="absolute top-0 right-0 w-64 h-64 rounded-full bg-sky-500/10 -mr-20 -mt-20 filter blur-2xl pointer-events-none" />
          <div className="absolute bottom-0 left-0 w-64 h-64 rounded-full bg-emerald-500/10 -ml-20 -mb-20 filter blur-2xl pointer-events-none" />
          
          <button
            onClick={onBack}
            className="flex items-center space-x-2 text-xs font-bold text-sky-400 hover:text-sky-300 transition-colors uppercase mb-4 cursor-pointer"
          >
            <ArrowLeft className={`w-4 h-4 ${isRtl ? 'rotate-180' : ''}`} />
            <span className={isRtl ? 'pr-1.5' : ''}>{isRtl ? 'العودة' : 'Back'}</span>
          </button>
          
          <h2 className="text-2xl sm:text-3xl font-black tracking-tight">{doc.title}</h2>
          <p className="text-xs text-slate-400 font-bold mt-1.5">{doc.subtitle}</p>
        </div>

        {/* Layout: Sidebar + Content */}
        <div className="grid grid-cols-1 md:grid-cols-4 min-h-[500px]">
          {/* Sidebar Tabs */}
          <div className="bg-slate-50 border-r md:border-r-0 md:border-b-0 border-slate-100 p-6 space-y-2">
            {tabs.map((tab) => {
              const Icon = tab.icon;
              const isActive = activeTab === tab.id;
              return (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`w-full flex items-center space-x-3 p-3.5 rounded-2xl text-xs font-extrabold transition-all text-left cursor-pointer ${
                    isActive
                      ? 'bg-sky-500 text-white shadow-md shadow-sky-500/10 ring-1 ring-sky-500/15'
                      : 'text-slate-600 hover:bg-slate-100'
                  } ${isRtl ? 'space-x-reverse' : ''}`}
                >
                  <Icon className="w-4 h-4 flex-shrink-0" />
                  <span>{tab.label}</span>
                </button>
              );
            })}
          </div>

          {/* Doc Content Area */}
          <div className="md:col-span-3 p-6 sm:p-8 space-y-6 overflow-y-auto max-h-[600px] text-left">
            <h3 className="text-lg font-black text-slate-800 tracking-tight pb-3 border-b border-slate-100 flex items-center space-x-2">
              <span>{doc.title}</span>
            </h3>

            <div className="space-y-6">
              {doc.sections.map((section, idx) => (
                <div key={idx} className="space-y-2">
                  <h4 className="text-sm font-black text-slate-800 tracking-tight">
                    {section.heading}
                  </h4>
                  <p className="text-xs text-slate-500 leading-relaxed font-medium">
                    {section.body}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </motion.div>
    </div>
  );
}
