import { GeneticReport, DailyBehaviorLog, CareNote, SecurityAuditLog } from './types';

export const TRANSLATIONS = {
  en: {
    brandName: 'AutiCare',
    navHome: 'Home',
    navFeatures: 'Features',
    navPricing: 'Pricing',
    navAbout: 'About Us',
    navContact: 'Contact us',
    navPlatform: 'Care Portal',
    login: 'Log in',
    signUp: 'Sign Up',

    // Hero Section
    heroTitle: 'AI-Powered Autism Support for Better Care',
    heroSub: 'AutiCare AI combines genetic nutrition intelligence with multi-provider care coordination, empowering doctors, therapists, and families together.',
    bookDemo: 'Book Demo',
    downloadApp: 'Download our application',
    quoteText: 'Experience personalized medical care from the comfort of your home.',

    // Core Purpose
    purposeTitle: 'Built with Purpose, Driven by Science',
    purposeText: 'AutiCare AI was founded by a team of physicians, AI engineers, and parents of children with ASD, united by the belief that better data leads to better outcomes.',
    missionTitle: 'Our Mission',
    missionDesc: 'To empower every physician, therapist, and parent with AI-driven insights that make autism care more personalized, coordinated, and effective, improving quality of life for children with ASD worldwide.',
    visionTitle: 'Our Vision',
    visionDesc: 'A world where every child with autism receives care tailored to their unique genetic makeup, supported by a coordinated team of providers working from a single, intelligent platform.',

    // The Problem Section
    problemHeader: 'The Problem',
    problemSub: 'Autism Care is Broken',
    problemText: 'Families with children on the autism spectrum face overwhelming fragmentation across providers, tools, and information.',
    probCard1Title: 'Fragmented Care',
    probCard1Desc: 'Doctors, therapists, and parents work in silos with no unified system to share insights.',
    probCard2Title: 'One-Size-Fits-All Nutrition',
    probCard2Desc: 'Generic nutrition advice ignores each child\'s unique genetic profile and specific metabolic needs.',
    probCard3Title: 'Late Detection',
    probCard3Desc: 'Behavioral crises are discovered too late. No predictive tools exist to intervene early.',
    probCard4Title: 'Disconnected Ecosystem',
    probCard4Desc: 'Parents manually track meals, sleep, and medications across disconnected apps with no AI guidance.',

    // Our Solution Section
    solutionHeader: 'Services',
    solutionSub: 'We offer top services',
    solutionText: 'From genetic analysis to behavioral prediction, all in one secure, compliant platform.',

    solCard1Title: 'AI Genetic Nutrition',
    solCard1Desc: 'Analyzes MTHFR, VDR, HLA-DQ2, FADS, and 6+ more markers to generate supplement and dietary plans.',
    solCard2Title: 'Behavioral Analytics',
    solCard2Desc: 'Track mood, sleep, meltdowns, and therapy attendance with AI-powered trend analysis.',
    solCard3Title: 'Care Coordination',
    solCard3Desc: 'Doctor, therapist, parent, and child dashboards with real-time notes and alerts.',
    solCard4Title: 'Predictive Alerts',
    solCard4Desc: 'ML-powered meltdown and regression risk scores with intervention recommendations.',
    solCard5Title: 'Child Development',
    solCard5Desc: '5 interactive cognitive games tracking memory, attention, and emotional recognition.',
    solCard6Title: 'HIPAA Security',
    solCard6Desc: 'End-to-end encryption, audit logs, role-based access, and secure file storage.',

    // Research Basis
    researchHeader: 'Research Basis',
    researchSub: 'Grounded in Genetic Science',
    researchText: 'Our nutrition engine is built on published research connecting specific genetic polymorphisms with autism-related metabolic pathways.',
    resCard1Title: 'MTHFR & Folate Metabolism',
    resCard1Desc: 'Studies link MTHFR C677T mutations to impaired methylation, affecting neurodevelopment. Methyl folate supplementation shows significant improvement in oxidative stress markers in ASD children.',
    resCard2Title: 'Vitamin D & Autism',
    resCard2Desc: 'VDR gene variants are associated with reduced Vitamin D receptor function. Adequate Vitamin D levels correlate with improved behavioral outcomes in multiple ASD trials.',
    resCard3Title: 'Gluten-Free & HLA Genes',
    resCard3Desc: 'Children with HLA-DQ2/DQ8 positive markers show elevated intestinal permeability. GFCF diets demonstrate measurable behavioral benefits in genetically susceptible individuals.',

    // Impact
    impactTitle: 'Our Impact',
    statChild: '500+ Children Supported',
    statMarkers: '10 Genetic Markers',
    statRoles: '4 Care Roles',
    statClinics: '40+ Clinics Online',
    statApproval: '98% Physician Approval',

    // Workflow
    workflowTitle: 'Workflow',
    workflowSub: 'Navigating your healthcare journey with HealNet is seamless. Just follow these steps mentioned below to proceed with your selected services.',
    wfStep1: 'Doctor uploads genetic PDF report',
    wfStep2: 'OCR extracts genetic marker data',
    wfStep3: 'AI rule engine maps markers → interventions',
    wfStep4: 'Doctor reviews and edits AI suggestions',
    wfStep5: 'Doctor approves the final plan',
    wfStep6: 'Parent receives approved nutrition plan',

    // Member Team Tabs
    teamHeader: 'Built for every member of the care team',
    teamSub: 'Six powerful feature modules from genetic AI to child games. All in one unified, secure platform.',
    roleDoctor: 'Doctor',
    roleDocDesc: 'Uploads genetic reports & approves AI plans',
    roleParent: 'Parent',
    roleParentDesc: 'Tracks daily logs, meals & medications',
    roleTherapist: 'Therapist',
    roleTherapistDesc: 'Logs behavioral sessions & progress',
    roleChild: 'Child',
    roleChildDesc: 'Plays cognitive games for tracking',

    // Testimonials
    testimonialHeader: 'Testimonials',
    testimonialSub: 'Discover the difference we make through the voices of those we\'ve served:',

    // Reach out
    reachTitle: 'Reach our Help Desk for support',
    reachSub: 'Questions? Need assistance? Our dedicated support team is here to help you every step of the way:',
    placeholderName: 'Enter Your First Name',
    placeholderEmail: 'Enter Your Email Address',
    placeholderPhone: 'Enter Your Contact Number',
    placeholderMsg: 'Tell us more about how we can help you.',
    submit: 'Submit',
    scheduleDemo: 'Schedule Demo',
    contactSuccess: 'Thank you! Your request has been received. Our clinical team will contact you within 2 hours.',

    // Info card contact
    contactHeader: 'Easily contact us in simple steps.',
    contactEmail: 'Email',
    contactHQ: 'Headquarters',
    contactHQVal: 'Alexandria, Egypt',
    contactHours: 'Support Hours',
    contactHoursVal: '24/7 for Hospital & Enterprise plans',

    // Pricing
    pricingTitle: 'Simple & Transparent Pricing',
    pricingSub: 'Choose the plan that fits your organization. All plans include full HIPAA compliance and our core AI features.',
    secPractice: 'For Doctors & Therapists',
    secFamilies: 'For Parents & Children',
    mostPopular: 'Most Popular',
    getStarted: 'Get Started',

    // Clinic Lists
    clinicTitle: 'Clinic Plan',
    clinicDesc: 'Perfect for single autism specialty clinics',
    hospTitle: 'Hospital Plan',
    hospDesc: 'For hospitals and multi-department facilities',
    entTitle: 'Enterprise Plan',
    entDesc: 'For large healthcare networks and governments',

    // Parent Lists
    parentTitle: 'Parent-Child Plan',
    parentDesc: 'Perfect for individuals managing autism care',
    familyTitle: 'Family Plan',
    familyDesc: 'Perfect for families managing multiple children with autism',

    // FAQs
    faqHeader: 'FAQ',
    faqQ1: 'Is AutiCare AI HIPAA compliant?',
    faqA1: 'Yes. All plans include full HIPAA compliance with encryption at rest and in transit, audit logs, and business associate agreements.',
    faqQ2: 'Is there a free trial?',
    faqA2: 'Yes, we offer a 14-day free trial on Clinic and Hospital plans. No credit card required.',
    faqQ3: 'Can I switch plans later?',
    faqA3: 'Absolutely. You can upgrade or downgrade your plan at any time. Upgrades take effect immediately.',
    faqQ4: 'Do you support other languages?',
    faqA4: 'Yes, the platform fully supports English and Arabic with complete RTL layout and typography.',

    // Interactive Portal Labels
    hubTitle: 'AutiCare Interactive Care Hub & Simulator',
    hubIntro: 'Simulate key platform features inside the sandbox. Toggle between Doctor, Therapist, and Parent roles to see the connected experience!',
    portalGenetic: 'Genetic Nutrition Parser',
    portalBehavior: 'Behavior Tracker & Predictor',
    portalCareCoord: 'Care Team Coordinator',
    portalGames: 'Cognitive Games Workspace',
    portalSecurity: 'Security & HIPAA Workspace',
    roleBtnLabel: 'Active Role Sim:',
    activePatientLabel: 'Active Patient Focus:',
    alertRiskTitle: 'Meltdown Risk Index',
    alertRiskSub: 'Predictive 7-day model outcome',
    earlyWarning: 'Early Warning Notification',
    triggerCalm: 'Meltdown Risk Low. Keep current sensory settings.',
    triggerAlert: 'CRITICAL ALERT: Meltdown probability 82% in next 12 hours based on circadian and behavioral regression notes. Recommended Intervention: Initiate quiet visual decompression and gluten-free snack.',
    footerSupport: 'Support',
    footerPlatform: 'Platform',
    footerSolutions: 'Solutions',
    footerLegal: 'Legal',
    footerGettingStarted: 'Getting Started',
    footerFAQs: 'FAQs',
    footerHelpArticles: 'Help Articles',
    footerReportIssue: 'Report an issue',
    footerContactHelpDesk: 'Contact Help Desk',
    footerFeatures: 'Features',
    footerPricing: 'Pricing',
    footerAboutUs: 'About Us',
    footerForDoctors: 'For Doctors',
    footerForTherapists: 'For Therapists',
    footerForParents: 'For Parents',
    footerForHospitals: 'For Hospitals',
    footerTerms: 'Terms & Conditions',
    footerPrivacy: 'Privacy Policy',
    footerCookieNotice: 'Cookie Notice',
    footerHIPAA: 'HIPAA Compliance',
    footerRights: 'AutiCare 2026 © All Rights Reserved',
    test1Quote: 'AutiCare AI transformed how I manage my ASD patients. The genetic nutrition planning alone saved me hours of research per patient.',
    test1Author: 'Pediatric Neurologist',
    test2Quote: 'For the first time, I feel like our whole care team is on the same page. The parent dashboard makes daily tracking so easy and meaningful.',
    test2Author: 'Parent',
    test3Quote: 'The behavioral analytics help me see patterns I would have missed. My session plans are so much more targeted now.',
    test3Author: 'ABA Therapist',
    test4Quote: 'We deployed AutiCare AI across our 3 clinics. The coordination improvement is remarkable. Highly recommended for any autism specialty center.',
    test4Author: 'Medical Director',
    // Authentication flow
    authHeaderJoin: 'Join AutiCare',
    authSubRole: 'Choose your role to get started',
    authParent: 'Parent',
    authParentDesc: "Sign up to track and support your child's progress",
    authDoctor: 'Doctor',
    authDoctorDesc: 'Access specialized tools to support child development',
    authTherapist: 'Therapist',
    authTherapistDesc: 'Access specialized tools to support child development',
    authNext: 'Next Step',
    authAlready: 'Already have an account? Log in',
    authNoAccount: "Don't have an account? Sign up",
    authJoinParent: 'Join AutiCare as Parent',
    authJoinClinician: 'Join AutiCare as Doctor / Therapist',
    authCreateStart: 'Create an account to start your journey',
    authParentInfo: 'Parent Info',
    authChildInfo: 'Child Info',
    authFullName: 'Full Name',
    authEmail: 'Email Address',
    authPassword: 'Password',
    authConfirmPassword: 'Confirm Password',
    authChildName: "Child's Name",
    authChildAge: "Child's Age",
    authDiagnosisLevel: 'Diagnosis Level',
    authGender: 'Gender',
    authChildPhoto: "Child's Photo (Optional)",
    authBirthCert: 'Birth certificate',
    authTermsCheck: 'I agree to terms of service and privacy policy',
    authSignUp: 'Sign Up',
    authPersonalInfo: 'Personal Info',
    authProfessionalInfo: 'Professional Info',
    authGenderSelect: 'Select Gender',
    authLevelSelect: 'Select Level',
    authTitleSelect: 'Select Title',
    authSpecSelect: 'Select Specialization',
    authTitle: 'Professional Title',
    authSpecialization: 'Specialization',
    authClinicName: 'Clinic Name',
    authClinicAddress: 'Clinic Address',
    authYearsExp: 'Years of Experience',
    authUploadPhoto: 'Upload Photo',
    authUploadPhotoDesc: "Drag and drop or click to upload child's photo (Optional)",
    authUploadDoc: 'Upload Document',
    authUploadDocDesc: 'Drag and drop or click to upload ID/Document verification',
    authNationalID: 'National ID / Passport',
    authMedicalLicense: 'Medical License / Certificate',
    authCV: 'CV / Resume',
    authSuccessTitle: 'Accounts Created Successfully!',
    authSuccessSub: 'Your parent and child accounts are ready',
    authParentAccountDetails: 'Parent Account Details',
    authChildAccountDetails: 'Child Account Credentials',
    authSaveCreds: 'Please save these credentials for your child to log in',
    authGoDashboard: 'Go to Dashboard',
    authChildUsername: "Child's Username",
    authChildPassword: "Child's Password",
    authPendingTitle: 'Verification Pending',
    authPendingThank: 'Thank you for registering with AutiCare!',
    authPendingReview: 'Your account is currently under review by our admin team to verify your credentials. This process usually takes 24-48 hours.',
    authPendingNotify: 'We will notify you via email once your account has been approved.',
    authBackHome: 'Back to Home',
    authWelcomeBack: 'Welcome Back',
    authSelectLoginRole: 'Select your role to log in',
    authLoginParent: 'Parent / Child',
    authLoginParentDesc: "Log in to track your child's progress or play games",
    authLoginDoctor: 'Doctor',
    authLoginDoctorDesc: 'Access specialized tools to support child development',
    authLoginTherapist: 'Therapist',
    authLoginTherapistDesc: 'Access specialized tools to support child development',
    authWelcomeDoc: 'Welcome Back Doctor',
    authWelcomeTherapist: 'Welcome Back Therapist',
    authLoginDocSub: 'Log in to access your doctor dashboard',
    authLoginTherapistSub: 'Log in to access your therapist dashboard',
    authLoginParentSub: 'Log in to access your parent / child account',
    authUsernameOrEmail: 'Email Address / Username',
    authRemember: 'Remember me',
    authForgot: 'Forgot Password?',
    authLoginBtn: 'Log In',
    // Notifications
    notifFeedTitle: 'Live Alerts Feed',
    notifMarkAllRead: 'Mark all read',
    notifEmpty: 'No recent notifications found.',
    notifViewAll: 'View all notifications',
    notifTypeProfile: 'Profile update',
    notifTypeClinical: 'Clinical insight',
    notifTypeDietary: 'Dietary plan',
    notifTypeActivity: 'Activity report',
    notifViewDetails: 'View details',
    notifSettings: 'Notification preferences',
    notifClearAll: 'Clear',
    notifTypeTestResult: 'Test Result',
    notifDescTestResult: 'Your test results are ready',
    notifTypeSchedule: 'Schedule Update',
    notifDescSchedule: 'New appointment/session schedule',
    notifTypeReminder: 'Reminder',
    notifDescReminder: "Don't forget your appointment",
    notifTypeProgress: 'Progress Update',
    notifDescProgress: 'New progress report available',
    notifTypeCarePlan: 'Care Plan',
    notifDescCarePlan: 'New care plan created/updated',
    notifTypeBehavior: 'Behavioral Insight',
    notifDescBehavior: 'New behavioral pattern detected',
    notifTypeMilestone: 'Milestone',
    notifDescMilestone: 'Your child reached a new milestone',
    notifTypeAnnouncement: 'Announcement',
    notifDescAnnouncement: 'Important update from admin',
  },
  ar: {
    brandName: 'أوتي كير',
    navHome: 'الرئيسية',
    navFeatures: 'المميزات',
    navPricing: 'الأسعار',
    navAbout: 'من نحن',
    navContact: 'اتصل بنا',
    navPlatform: 'بوابة الرعاية',
    login: 'تسجيل الدخول',
    signUp: 'حساب جديد',

    // Hero Section
    heroTitle: 'دعم التوحد بالذكاء الاصطناعي لرعاية أفضل',
    heroSub: 'تجمع منصة أوتي كير AI بين ذكاء التغذية الجينية وتنسيق الرعاية متعددة الأطراف لتمكين الأطباء والمعالجين والأهالي معًا.',
    bookDemo: 'حجز تجربة',
    downloadApp: 'تحميل تطبيقنا الخاص للأجهزة',
    quoteText: 'احصل على رعاية طبية مخصصة من راحة منزلك بكل سهولة.',

    // Core Purpose
    purposeTitle: 'بني بهدف، ويقاد بالعلم والدليل',
    purposeText: 'تأسست أوتي كير من قبل فريق من الأطباء، مهندسي الذكاء الاصطناعي، وأولياء أمور أطفال ذوي طيف التوحد، مدفوعين بالإيمان بأن دقة البيانات تؤدي لنتائج أفضل.',
    missionTitle: 'مهمتنا',
    missionDesc: 'تمكين كل طبيب، أخصائي، وولي أمر برؤى قائمة على الذكاء الاصطناعي لتصبح رعاية التوحد مخصصة، منسقة، وفعالة بشكل أكبر، مما يحسن جودة حياة الأطفال عالمياً.',
    visionTitle: 'رؤيتنا',
    visionDesc: 'عالم يحصل فيه كل طفل مصاب بالتوحد على رعاية مخصصة ومصممة بدقة لتناسب بصمته الجينية الفريدة، بدعم من فريق رعاية متكامل يعمل عبر منصة ذكية موحدة.',

    // The Problem Section
    problemHeader: 'المشكلة الحالية',
    problemSub: 'رعاية التوحد مشتتة وغير مترابطة',
    problemText: 'تواجه عائلات أطفال طيف التوحد تشتتًا هائلاً في أدوات التواصل والتقارير الطبية والمتابعة اليومية.',
    probCard1Title: 'رعاية متجزئة ومشتتة',
    probCard1Desc: 'يعمل الأطباء، الاخصائيون، والأهالي في جزر معزولة دون تواصل أو تبادل فوري للتقارير والتحليلات.',
    probCard2Title: 'تغذية عشوائية موحدة للجميع',
    probCard2Desc: 'تتجاهل النصائح الغذائية العامة تباين البصمة الجينية لكل طفل والاحتياجات الأيضية الفريدة له.',
    probCard3Title: 'اكتشاف متأخر للأزمات',
    probCard3Desc: 'يتم اكتشاف أزمات الانهيار السلوكي بعد فوات الأوان. لا تتوفر أدوات تنبؤية للتدخل والاستباق.',
    probCard4Title: 'نظام بيئي منفصل كلياً',
    probCard4Desc: 'يقوم الآباء بتدوين الوجبات والنوم يدويًا على تطبيقات متعددة متباعدة وتفتقد كلياً لنصح الذكاء الاصطناعي.',

    // Our Solution Section
    solutionHeader: 'خدماتنا',
    solutionSub: 'أفضل الخدمات الطبية والذكية',
    solutionText: 'من التحليلات الجينية إلى التنبؤ بنوبات الغضب، كل هذا في منصة واحدة آمنة ومشفرة بالكامل.',

    solCard1Title: 'الذكاء الجيني للتغذية',
    solCard1Desc: 'تحليل المؤشرات الجينية MTHFR, VDR, HLA-DQ2, FADS لتصميم خطط مكملات وجداول غذائية مخصصة.',
    solCard2Title: 'التحليلات والتقارير السلوكية',
    solCard2Desc: 'متابعة المزاج وفترات النوم والانهيارات وحضور الجلسات مع رسوم واتجاهات ذكية محسنة.',
    solCard3Title: 'تنسيق متكامل للرعاية',
    solCard3Desc: 'بوابات متزامنة للطبيب والمعالج والوالد والطفل مع مذكرات وتنبيهات مباشرة لحظية.',
    solCard4Title: 'إنذارات تنبؤية مبكرة',
    solCard4Desc: 'حساب مؤشرات حتمية الأزمات ومحاكاة نوبات الغضب لتزويد المعالجين والوالدين بخطوات التدخل.',
    solCard5Title: 'ألعاب تنمية المهارات السلوكية',
    solCard5Desc: '5 ألعاب معرفية تفاعلية تختبر الذاكرة، وتركيز الانتباه، وتمييز تعابير المشاعر.',
    solCard6Title: 'الحماية المتكاملة HIPAA',
    solCard6Desc: 'تشفير كامل للبيانات، سجل تدقيق أمني للعمليات، ومستودع سحابي مخصص ومحمي.',

    // Research Basis
    researchHeader: 'الأساس البحثي والعلمي',
    researchSub: 'راسخ في علم الوراثة والجينات',
    researchText: 'تم بناء محرك التغذية والاهتمام لدينا على أبحاث رصينة منشورة تربط الطفرات الجينية بمسارات التمثيل الغذائي للتوحد.',
    resCard1Title: 'جين MTHFR وهضم الفولات',
    resCard1Desc: 'تربط الدراسات طفرات MTHFR C677T بضعف عمليات الميثيل وعرقلة النمو العصبي. يدعم الفولات النشط تحسنًا وظيفيًا ملحوظًا لدى الأطفال.',
    resCard2Title: 'فيتامين د ومستقبلات VDR',
    resCard2Desc: 'ترتبط التغيرات بجين VDR بكسل مستقبلات فيتامين د. أظهرت الفحوصات أن كفاية فيتامين د تسرع الاستجابات السلوكية الإيجابية.',
    resCard3Title: 'بروتين الغلوتين وجينات HLA',
    resCard3Desc: 'أطفال طفرات HLA-DQ2/DQ8 لديهم نفاذية معوية مفرطة تجاه الغلوتين والكازين. إقصاء هذه المواد يحقق منافع سلوكية قياسية ومثبتة.',

    // Impact
    impactTitle: 'الأثر والنجاحات',
    statChild: 'دعم أكثر من 500 طفل',
    statMarkers: '10 مؤشرات جينية محللة',
    statRoles: '4 أدوار رعاية منسقة',
    statClinics: '40 عيادة متصلة بالمنصة',
    statApproval: '98% نسبة موافقة واعتماد الأطباء',

    // Workflow
    workflowTitle: 'خطوات العمل ومسار الرعاية',
    workflowSub: 'نقل رعاية طفلك مع أوتي كير سهل ومباشر. اتبع الخطوات السلسة التالية للبدء بالخطط الطبية المبتكرة:',
    wfStep1: 'يقوم الطبيب برفع تقرير الحمض النووي PDF',
    wfStep2: 'يستخرج محرك الـ OCR البيانات والمؤشرات بدقة',
    wfStep3: 'يربط الذكاء الاصطناعي الجينات بالحلول والمغذيات الأيضية',
    wfStep4: 'يراجع الطبيب المقترحات الموصى بها ويعدلها إن لزم',
    wfStep5: 'يعتمد الطبيب الخطة النهائية بنقرة واحدة',
    wfStep6: 'يستلم الوالد جدول الأطعمة والمكملات الحصري للطفل',

    // Member Team Tabs
    teamHeader: 'مصمم لكل فرد وفريق رعاية',
    teamSub: 'ستة أقسام متكاملة لحوسبة رعاية أطفال طيف التوحد ببيئة سحابية آمنة.',
    roleDoctor: 'الطبيب والمنسق',
    roleDocDesc: 'يعتمد خطط التغذية ويحلل الفحوص الوريثية والبيولوجية للطفل',
    roleParent: 'ولي الأمر',
    roleParentDesc: 'يدون تطور نوبة الغضب والمزاج والوجبات اليومية',
    roleTherapist: 'المعالج السلوكي',
    roleTherapistDesc: 'يوثق تفاصيل جلسات الـ ABA وتحليل السلوك الوظيفي',
    roleChild: 'الطفل',
    roleChildDesc: 'يلعب ألعاب معرفية ترسل تقارير الدقة والمهارة للذكاء الاصطناعي',

    // Testimonials
    testimonialHeader: 'آراء شركائنا وعائلاتنا',
    testimonialSub: 'اكتشف التحول الإيجابي الحقيقي عبر الكلمات الملهمة لمن خدمناهم بشغف:',

    // Reach out
    reachTitle: 'تواصل مع مكتب الدعم الفني',
    reachSub: 'لديك أي استفسارات أو تفضل التسجيل؟ فريقنا وأخصائيو الرعاية وممثلو الدعم جاهزون دائمًا لمساندتك:',
    placeholderName: 'أدخل اسمك الكريم هنا',
    placeholderEmail: 'أدخل بريدك الإلكتروني المفضل',
    placeholderPhone: 'أدخل رقم الهاتف أو الجوال لنتواصل معك',
    placeholderMsg: 'أخبرنا عن تفاصيل الحالة وكيف يمكننا مساندتكم',
    submit: 'إرسال الطلب',
    scheduleDemo: 'جدولة عرض تجريبي',
    contactSuccess: 'شكرًا جزيلاً! تم استلام طلبكم بنجاح. سيتواصل فريقنا الطبي والاستشاري معكم خلال ساعتين كحد أقصى.',

    // Info card contact
    contactHeader: 'يمكنك التواصل معنا بخطوات يسيرة ميسرة.',
    contactEmail: 'البريد الإلكتروني',
    contactHQ: 'المقر الرئيسي للمؤسسة',
    contactHQVal: 'الإسكندرية، جمهورية مصر العربية',
    contactHours: 'أوقات العمل والدعم المتاحة',
    contactHoursVal: '24/7 لخطط المستشفيات والشركاء والمؤسسات',

    // Pricing
    pricingTitle: 'خطط أسعار واضحة وشفافة',
    pricingSub: 'اختر الباقة المثالية التي تلبي تطلعات عيادتك أو عائلتك. تشمل جميع الباقات امتثال HIPAA كامل ومميزات التنبؤ.',
    secPractice: 'للأطباء والمراكز العلاجية والأخصائيين',
    secFamilies: 'لأولياء الأمور والمتابعة المنزلية للأطفال',
    mostPopular: 'الأكثر اختيارًا وشعبية',
    getStarted: 'ابدأ الآن',

    // Clinic Lists
    clinicTitle: 'خطة العيادة الفردية',
    clinicDesc: 'مثالية لمراكز وعيادات التوحد المستقلة',
    hospTitle: 'خطة المستشفيات',
    hospDesc: 'مخصصة للمستشفيات والأقسام الطبية متعددة الفروع والتخصصات',
    entTitle: 'الخطة المؤسسية الشاملة',
    entDesc: 'لشبكات الرعاية الصحية الكبرى، والمراكز الحكومية، والهيئات المعتمدة',

    // Parent Lists
    parentTitle: 'خطة الوالد والطفل',
    parentDesc: 'مثالية للمتابعة الذاتية الفردية وادخار الرعاية المنزلية بمرونة',
    familyTitle: 'خطة العائلة المتكاملة',
    familyDesc: 'مثالية للعائلات التي تطمح لمتابعة ورعاية أكثر من طفل مصاب بالطيف في آن واحد',

    // FAQs
    faqHeader: 'الأسئلة الشائعة والأجوبة',
    faqQ1: 'هل منصة أوتي كير معتمدة وهل تضمن خصوصية المريض و HIPAA؟',
    faqA1: 'بكل تأكيد. جميع الباقات والأنظمة ممتثلة لمعايير HIPAA الطبية العالمية مع تشفير متكامل في الإرسال والتدوين السحابي وسجلات للمتابعة الأمنية والتقارير الطبية.',
    faqQ2: 'هل تتوفر فترة تجريبية مجانية؟',
    faqA2: 'نعم، نوفر تجربة مجانية مميزة لمدة 14 يومًا لخطط العيادات والمستشفيات للوقوف على دقة المنصة ومواءمتها لكم دون الحاجة لإدخال بطاقتكم المصرفية.',
    faqQ3: 'هل يمكنني تغيير أو ترقية خطتي السنوية لاحقًا؟',
    faqA3: 'نعم ومن خلال لوحة التحكم مباشرة. يمكنك ترقية أو خفض اشتراك الباقة في أي لحظة. تدخل التعديلات حيز التفعيل فورًا وباحتساب نسبي دقيق.',
    faqQ4: 'هل تدعم المنصة لغات أخرى إلى جانب الانجليزية؟',
    faqA4: 'المنصة تدعم بشكل أساسي ومتكامل اللغات العربية والإنجليزية، مع تعليق وتشكيل الخطوط ودعم اتجاهات الشاشات من اليمين لليسار (RTL) بشكل مثير ومريح.',

    // Interactive Portal Labels
    hubTitle: 'ركن محاكاة وبوابة رعاية أوتي كير التفاعلية',
    hubIntro: 'اختبر الميزات الجينية والرقابية الاستباقية في بيئة المحاكاة التدريبية الآمنة لدينا وتصفح البوابات المتصلة للطبيب والمعالج والوالد والطفل!',
    portalGenetic: 'مفسر الجينات والتغذية الوراثية',
    portalBehavior: 'سجل رصد السلوك والتنبؤ بنوبتهم',
    portalCareCoord: 'منسق وملخص عمل فريق الرعاية',
    portalGames: 'تنمية المهارات والألعاب المعرفية للطفل',
    portalSecurity: 'فحوص الأمان والتوافق والامتثال HIPAA',
    roleBtnLabel: 'المحاكاة بدور:',
    activePatientLabel: 'تحديد الطفل المستهدف:',
    alertRiskTitle: 'الرصد ومؤشرات الحتمية للأزمة السلوكية',
    alertRiskSub: 'توقعات نماذج الذكاء الاصطناعي لمدة 7 أيام',
    earlyWarning: 'إشعار الإنذار والاستباق المبكر',
    triggerCalm: 'مؤشر أزمات السلوك طبيعي ومنخفض. ينصح بالبقاء ع توازن البيئة السمعية الحالية.',
    triggerAlert: 'أزمة انهيار مرتقبة وباحتمالية 82٪ خلال الـ 12 ساعة القادمة استنادًا لانحراف جدول النوم اليوم وتأخر الهضم. التوصية: ابدأ خطوات الهدوء البصري الفوري وقدم وجبة خفيفة خالية من الغلوتين.',
    footerSupport: 'الدعم',
    footerPlatform: 'المنصة',
    footerSolutions: 'الحلول',
    footerLegal: 'الشروط القانونية',
    footerGettingStarted: 'البدء والاستخدام',
    footerFAQs: 'الأسئلة الشائعة',
    footerHelpArticles: 'مقالات المساعدة',
    footerReportIssue: 'الإبلاغ عن مشكلة',
    footerContactHelpDesk: 'الاتصال بالدعم',
    footerFeatures: 'المميزات',
    footerPricing: 'الأسعار',
    footerAboutUs: 'من نحن',
    footerForDoctors: 'للأطباء',
    footerForTherapists: 'للمعالجين',
    footerForParents: 'لأولياء الأمور',
    footerForHospitals: 'للمستشفيات',
    footerTerms: 'الشروط والأحكام',
    footerPrivacy: 'سياسة الخصوصية',
    footerCookieNotice: 'ملفات تعريف الارتباط',
    footerHIPAA: 'امتثال HIPAA',
    footerRights: 'أوتي كير 2026 © جميع الحقوق محفوظة',
    test1Quote: 'لقد غيرت منصة أوتي كير AI طريقة تعاملي مع مرضى طيف التوحد تماماً. وفرت علي خطة التغذية الجينية ساعات من البحث والدراسة لكل حالة.',
    test1Author: 'أخصائي أمراض أعصاب الأطفال',
    test2Quote: 'لأول مرة أشعر أن فريق الرعاية بأكمله يعمل بتنسيق كامل وعلى نفس الصفحة. لوحة متابعة ولي الأمر تجعل المراقبة اليومية مريحة وذات مغزى.',
    test2Author: 'ولي أمر',
    test3Quote: 'تساعدني التحليلات السلوكية في رصد أنماط وتفاصيل كان من السهل إغفالها. أصبحت خطط الجلسات السلوكية لدي أكثر استقافة وفعالية.',
    test3Author: 'معالج تحليل السلوك التطبيقي (ABA)',
    test4Quote: 'قمنا بتشغيل منصة أوتي كير AI في عياداتنا الثلاث. تحسن تنسيق الرعاية بين أفراد الفريق بشكل مذهل ونوصي بها بشدة لكل مركز متخصص.',
    test4Author: 'المدير الطبي للمركز',
    // Authentication flow
    authHeaderJoin: 'انضم إلى أوتي كير',
    authSubRole: 'اختر دورك للبدء في استخدام المنصة',
    authParent: 'ولي أمر',
    authParentDesc: 'سجل لمتابعة ودعم مسار تقدم طفلك اليومي',
    authDoctor: 'طبيب',
    authDoctorDesc: 'الوصول لأدوات متخصصة لمساندة وتطوير مهارات الطفل',
    authTherapist: 'معالج سلوكي',
    authTherapistDesc: 'الوصول لأدوات متخصصة لمساندة وتطوير مهارات الطفل',
    authNext: 'الخطوة التالية',
    authAlready: 'لديك حساب بالفعل؟ سجل الدخول',
    authNoAccount: 'ليس لديك حساب؟ أنشئ حساباً جديداً',
    authJoinParent: 'انضم لأوتي كير كولي أمر',
    authJoinClinician: 'انضم لأوتي كير كطبيب / معالج',
    authCreateStart: 'أنشئ حسابك الآن للبدء برحلة الرعاية',
    authParentInfo: 'معلومات ولي الأمر',
    authChildInfo: 'معلومات الطفل',
    authFullName: 'الاسم الكامل',
    authEmail: 'البريد الإلكتروني',
    authPassword: 'كلمة المرور',
    authConfirmPassword: 'تأكيد كلمة المرور',
    authChildName: 'اسم الطفل',
    authChildAge: 'عمر الطفل',
    authDiagnosisLevel: 'مستوى التشخيص',
    authGender: 'الجنس',
    authChildPhoto: 'صورة الطفل (اختياري)',
    authBirthCert: 'شهادة الميلاد / وثيقة الهوية',
    authTermsCheck: 'أوافق على شروط الخدمة وسياسة الخصوصية',
    authSignUp: 'تسجيل الحساب',
    authPersonalInfo: 'البيانات الشخصية',
    authProfessionalInfo: 'البيانات المهنية',
    authGenderSelect: 'اختر الجنس',
    authLevelSelect: 'اختر المستوى',
    authTitleSelect: 'اختر المسمى المهني',
    authSpecSelect: 'اختر التخصص',
    authTitle: 'المسمى المهني',
    authSpecialization: 'التخصص الدقيق',
    authClinicName: 'اسم العيادة',
    authClinicAddress: 'عنوان العيادة',
    authYearsExp: 'سنوات الخبرة',
    authUploadPhoto: 'رفع الصورة',
    authUploadPhotoDesc: 'اسحب وأسقط أو انقر هنا لرفع صورة طفلك (اختياري)',
    authUploadDoc: 'رفع المستند',
    authUploadDocDesc: 'اسحب وأسقط أو انقر هنا لرفع وثيقة إثبات الهوية والتحقق',
    authNationalID: 'الهوية الوطنية / جواز السفر',
    authMedicalLicense: 'الترخيص الطبي / الشهادة',
    authCV: 'السيرة الذاتية / CV',
    authSuccessTitle: 'تم إنشاء الحسابات بنجاح!',
    authSuccessSub: 'حساب ولي الأمر وحساب الطفل جاهزان الآن للاستخدام',
    authParentAccountDetails: 'بيانات حساب ولي الأمر',
    authChildAccountDetails: 'بيانات اعتماد حساب الطفل',
    authSaveCreds: 'يرجى حفظ بيانات الاعتماد هذه ليتمكن طفلك من تسجيل الدخول',
    authGoDashboard: 'الذهاب للوحة التحكم',
    authChildUsername: 'اسم المستخدم للطفل',
    authChildPassword: 'كلمة مرور الطفل',
    authPendingTitle: 'التحقق قيد المراجعة',
    authPendingThank: 'شكرًا لتسجيلك مع أوتي كير!',
    authPendingReview: 'حسابك حاليًا قيد المراجعة والتدقيق من قبل فريق الإدارة للتحقق من مؤهلاتك وثائقك. تستغرق هذه العملية عادة من 24 إلى 48 ساعة.',
    authPendingNotify: 'سنقوم إخطارك عبر البريد الإلكتروني بمجرد الموافقة على حسابك وتفعيله بالكامل.',
    authBackHome: 'العودة للرئيسية',
    authWelcomeBack: 'مرحباً بعودتك',
    authSelectLoginRole: 'اختر دورك لتسجيل الدخول',
    authLoginParent: 'ولي الأمر / الطفل',
    authLoginParentDesc: 'سجل الدخول لمتابعة تقدم طفلك أو للعب الألعاب',
    authLoginDoctor: 'طبيب',
    authLoginDoctorDesc: 'الوصول للأدوات المتخصصة والتقارير الجينية',
    authLoginTherapist: 'معالج سلوكي',
    authLoginTherapistDesc: 'الوصول لجلسات تحليل السلوك ورصد التقدم',
    authWelcomeDoc: 'مرحباً بك مجدداً يا دكتور',
    authWelcomeTherapist: 'مرحباً بك مجدداً يا معالجنا العزيز',
    authLoginDocSub: 'سجل الدخول للوصول إلى لوحة تحكم الطبيب الخاصة بك',
    authLoginTherapistSub: 'سجل الدخول للوصول إلى لوحة تحكم المعالج الخاصة بك',
    authLoginParentSub: 'سجل الدخول للوصول لحساب ولي الأمر والطفل المشترك',
    authUsernameOrEmail: 'البريد الإلكتروني / اسم المستخدم',
    authRemember: 'تذكرني',
    authForgot: 'هل نسيت كلمة المرور؟',
    authLoginBtn: 'تسجيل الدخول',
    //Notifications
    notifFeedTitle: 'موجز التنبيهات المباشرة',
    notifMarkAllRead: 'تحديد الكل كمقروء',
    notifEmpty: 'لا توجد تنبيهات حديثة.',
    notifViewAll: 'عرض كل التنبيهات',
    notifTypeProfile: 'تحديث الملف الشخصي',
    notifTypeClinical: 'رؤية طبية',
    notifTypeDietary: 'الخطة الغذائية',
    notifTypeActivity: 'تقرير النشاط',
    notifViewDetails: 'عرض التفاصيل',
    notifSettings: 'تفضيلات التنبيهات',
    notifClearAll: 'مسح',
    notifTypeTestResult: 'نتيجة الاختبار',
    notifDescTestResult: 'نتائج الاختبارات الخاصة بك جاهزة الآن',
    notifTypeSchedule: 'تحديث الجدول الزمني',
    notifDescSchedule: 'مواعيد أو جلسات جديدة مضافة للجدول',
    notifTypeReminder: 'تذكير',
    notifDescReminder: 'تذكير: لا تنسى موعدك المحدد',
    notifTypeProgress: 'تحديث معدل التقدم',
    notifDescProgress: 'تقرير تقدم جديد متاح للمراجعة',
    notifTypeCarePlan: 'خطة الرعاية',
    notifDescCarePlan: 'تم إنشاء أو تحديث خطة الرعاية للطفل',
    notifTypeBehavior: 'رؤية سلوكية',
    notifDescBehavior: 'تم رصد وتحليل نمط سلوكي جديد',
    notifTypeMilestone: 'إنجاز جديد',
    notifDescMilestone: 'تهانينا! حقق طفلك إنجازاً تطورياً جديداً',
    notifTypeAnnouncement: 'إعلان عام',
    notifDescAnnouncement: 'تحديث إداري هام من فريق المنصة',
  }
};

export const SAMPLE_GENETIC_REPORTS: GeneticReport[] = [
  {
    id: 'REP-01',
    patientName: 'Sami Al-Farsi',
    mthfrStatus: 'Homozygous mutant (C677T/A1298C)',
    mthfrImpact: 'Severe alteration in folate coenzyme path causing methylation bottleneck and elevated oxidative factors.',
    vdrStatus: 'ff (Reduced Vitamin D Receptor)',
    vdrImpact: 'Sluggish metabolic binding. Calcium and neural vitamin retention are lowered by up to 60%.',
    hlaStatus: 'HLA-DQ2 Positive',
    hlaImpact: 'High risk of micro-inflammatory bowel symptoms on gluten exposure. High barrier permeability suspected.',
    dietRecommendations: [
      'Strict Gluten-Free and Casein-Free (GFCF) diet framework.',
      'Eliminate artificial flavorings, color additives, and high-MSG ingredients.',
      'Introduce bone broths, fermented sheep milk yogurt (if casein-tolerated) or coconut kefir to support mucosal healing.',
      'Incorporate organic sprouted seeds and dense cruciferous greens.'
    ],
    supplementGuidance: [
      'L-Methylfolate (as Metafolin®) - 400 mcg daily morning with breakfast to bypass metabolic MTHFR block.',
      'Liquid Vitamin D3 with K2 drops - 2000 IU sublingual to maximize the slow absorption kinetics of ff VDR receptors.',
      'Active Coenzyme Q10 and Probiotics with Bifidobacterium strains to secure neuro-gut barrier safety.'
    ],
    unsupportedFoods: [
      'Refined Wheat Flour, Barley, Rye (Gluten group).',
      'Whole Cow Milk, Casein powders, highly processed cheeses.',
      'Preservatives-rich baked treats, sugary drinks, high-fructose corn syrup.'
    ],
    mealPlan: [
      { day: 'Monday', meals: ['Breakfast: Coconut Chia Pudding with Fresh Raspberries', 'Lunch: Grilled Chicken Salad with Olive Oil and Sprouted Greens', 'Dinner: Wild Salmon over Steamed Cauliflower Mash'] },
      { day: 'Tuesday', meals: ['Breakfast: Fluffy Grain-Free Banana Pancakes', 'Lunch: Turkey Lettuce Wraps with Avocado Aioli', 'Dinner: Organic Beef Bone Broth Soup with Bok Choy'] },
      { day: 'Wednesday', meals: ['Breakfast: Spinach and Avocado Smoothie with Pumpkin Seeds', 'Lunch: Baked Sweet Potato with Shredded Carrot and Seed Butter', 'Dinner: Herb-Roasted Cod with Zucchini ribbons'] }
    ]
  },
  {
    id: 'REP-02',
    patientName: 'Maya Henderson',
    mthfrStatus: 'Heterozygous (C677T)',
    mthfrImpact: 'Mild decrease in active folate levels. Moderate methyl cycle stress noted during inflammatory triggers.',
    vdrStatus: 'Ff (Normal Expression)',
    vdrImpact: 'Stable and responsive receptor action. Standard nutritional intake levels support brain signaling properly.',
    hlaStatus: 'HLA-DQ2/DQ8 Negative',
    hlaImpact: 'No direct genetic autoimmune response to gluten identified. Intestinal barrier remains normal.',
    dietRecommendations: [
      'Whole-food diet focusing on organic proteins and balanced healthy lipids.',
      'Moderate natural grain intake allowed (prefer Ancient Oats, Quinoa).',
      'Boost intake of sulfur-rich vegetables (garlic, onions, broccoli) for natural detox paths.',
      'Keep hydration high with raw electrolyte-infused water.'
    ],
    supplementGuidance: [
      'Active Pyridoxal-5-Phosphate (P-5-P Coenzyme B6) - 25 mg to support healthy serotonin/dopamine transmission.',
      'Omega-3 EPA/DHA Pure Fish Oil - 1200 mg to lower microglial activation.'
    ],
    unsupportedFoods: [
      'Highly refined cane sugar, white bread.',
      'Saturated trans-fats, fried street foods.',
      'Carbonated pop sodas, synthetic dyes (Red 40, Yellow 5).'
    ],
    mealPlan: [
      { day: 'Monday', meals: ['Breakfast: Scrambled Organic Eggs with Steamed Spinach', 'Lunch: Quinoa and Grilled Chicken Bowl', 'Dinner: Slow Cooked Beef Cheek with Roasted Carrots'] },
      { day: 'Tuesday', meals: ['Breakfast: Blueberry Almond Milk Smoothie', 'Lunch: Grass-Fed Lamb sliders in Lettuce Buns', 'Dinner: Teriyaki Cod over Organic Brown Rice'] },
      { day: 'Wednesday', meals: ['Breakfast: Buckwheat Apple Porridge', 'Lunch: Mixed Green Salad with Boiled Eggs and Sunflower Seeds', 'Dinner: Oven Roasted Turkey with Brussels Sprouts'] }
    ]
  }
];

export const INITIAL_BEHAVIOR_LOGS: DailyBehaviorLog[] = [
  { id: 'LOG-01', date: '2026-06-15', mood: 'excellent', sleepHours: 9, mealsLogged: ['breakfast', 'lunch', 'dinner'], meltdownSeverity: 'none', therapyMinutes: 45, medicationCompliance: true, notes: 'Sami was focused, energetic, loved the cognitive memory game. Normal sensory responses.', meltdownRiskScore: 12 },
  { id: 'LOG-02', date: '2026-06-16', mood: 'good', sleepHours: 8.5, mealsLogged: ['breakfast', 'lunch', 'dinner', 'snacks'], meltdownSeverity: 'none', therapyMinutes: 0, medicationCompliance: true, notes: 'Stayed calm during grocery shopping. Gluten-free meal tolerated perfectly.', meltdownRiskScore: 18 },
  { id: 'LOG-03', date: '2026-06-17', mood: 'neutral', sleepHours: 7, mealsLogged: ['breakfast', 'lunch'], meltdownSeverity: 'mild', therapyMinutes: 30, medicationCompliance: true, notes: 'Bit of restlessness around sunset. Agitated due to emergency truck sirens outside.', meltdownRiskScore: 45 },
  { id: 'LOG-04', date: '2026-06-18', mood: 'unsettled', sleepHours: 6, mealsLogged: ['breakfast', 'snacks'], meltdownSeverity: 'moderate', therapyMinutes: 45, medicationCompliance: false, notes: 'Refused morning supplement. Sleep disrupted. 20-minute verbal meltdown at school transition.', meltdownRiskScore: 78 },
  { id: 'LOG-05', date: '2026-06-19', mood: 'excellent', sleepHours: 9.5, mealsLogged: ['breakfast', 'lunch', 'dinner'], meltdownSeverity: 'none', therapyMinutes: 60, medicationCompliance: true, notes: 'Excellent rest, Metafolin dose given early. Highly compliant in speech therapy session.', meltdownRiskScore: 10 },
  { id: 'LOG-06', date: '2026-06-20', mood: 'good', sleepHours: 8, mealsLogged: ['breakfast', 'lunch', 'dinner'], meltdownSeverity: 'none', therapyMinutes: 0, medicationCompliance: true, notes: 'Happy mood all afternoon. Played shape matching game with sister.', meltdownRiskScore: 15 },
  { id: 'LOG-07', date: '2026-06-21', mood: 'neutral', sleepHours: 7.5, mealsLogged: ['breakfast', 'lunch', 'dinner'], meltdownSeverity: 'mild', therapyMinutes: 30, medicationCompliance: true, notes: 'Mild stimming in evening, calm down protocol worked quickly after 5 minutes.', meltdownRiskScore: 28 }
];

export const CARE_NOTES: CareNote[] = [
  {
    id: 'NT-01',
    authorName: 'Dr. Karim Al-Saeed',
    authorRole: 'Doctor',
    content: 'Analyzed DNA report. Note severe downregulation in MTHFR and HLA-DQ2 positive status. Initiating methylation protocol with 400mcg methylfolate. Check-up appointment set in 2 weeks.',
    timestamp: '2026-06-21 09:30',
    category: 'Medical',
    approvedByDoctor: true
  },
  {
    id: 'NT-02',
    authorName: 'Amina El-Gamil',
    authorRole: 'Therapist',
    content: 'Conducted ABA therapy focusing on eye contact and social turn-taking. Played two cognitive emotion boards. Sami responded brilliantly, accuracy scores improved to 85% compared to yesterday.',
    timestamp: '2026-06-21T11:45:00Z',
    category: 'Therapy',
    approvedByDoctor: false
  },
  {
    id: 'NT-03',
    authorName: 'Youssef Al-Farsi',
    authorRole: 'Parent',
    content: 'Followed GFCF dinner exactly. Sami slept better last night (8 hours straight). No daytime meltdowns recorded. Supplements administered successfully with coconut water proxy.',
    timestamp: '2026-06-21T19:15:00Z',
    category: 'Dietary',
    approvedByDoctor: false
  }
];

export const SECURITY_AUDIT_LOGS: SecurityAuditLog[] = [
  { id: 'AUD-01', action: 'User login (JWT Generated)', performedBy: 'dr.karim@auticare.org', timestamp: '2026-06-21 15:20:01', ipAddress: '197.34.112.5', status: 'SUCCESS' },
  { id: 'AUD-02', action: 'PDF Genetic Report Upload (Encrypted at Rest)', performedBy: 'dr.karim@auticare.org', timestamp: '2026-06-21 15:22:15', ipAddress: '197.34.112.5', status: 'SUCCESS' },
  { id: 'AUD-03', action: 'OCR extraction & AI recommendation mapping', performedBy: 'AI Engine - Cloud Worker v4', timestamp: '2026-06-21 15:22:18', ipAddress: 'System-VPC', status: 'SUCCESS' },
  { id: 'AUD-04', action: 'Accessed HIPAA protected patient file - Sami Al-Farsi', performedBy: 'amina.therapist@auticare.org', timestamp: '2026-06-21 15:25:30', ipAddress: '197.60.44.18', status: 'SUCCESS' },
  { id: 'AUD-05', action: 'Parent medication log update', performedBy: 'youssef.parent@auticare.org', timestamp: '2026-06-21 15:28:44', ipAddress: '102.43.200.198', status: 'SUCCESS' }
];
